/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package latihanKu;

/**
 *
 * @author ASUS
 */
public class aboutPanel extends javax.swing.JPanel {

    /**
     * Creates new form aboutPanel
     */
    public aboutPanel() {
        initComponents();
        about();
    }

    void about(){
        String aboutText = "<html>"
                + "<body>"
                + "<p><b>AKAT - Aplikasi Kasir Al Wandee TENNAN</b> adalah aplikasi kasir sederhana yang dibuat untuk membantu <br> pengelolaan Warung Kopi sekaligus Rental PlayStation, pada UMKM Warung Kopi dan Rental PlayStation<br> <b>Al-Wandee TENNAN</b><br><br>  Aplikasi ini dibuat oleh Mahasiswa <b>INSTITUT TEKNOLOGI MOJOSARI</b>, antara lain : <br></p>"
                + "<pre style =\"font-family : 'Segoe UI;'\">"
                + " Ahmad Saifuddin Azyuhdi\t:     (202457201008)\n"
                + " Anna Cahya Ningrum\t:     (202457201013)\n"
                + " Anti Maulidatul Husna\t:     (202457201014)\n"
                + " Aufi Dhuha Mutaafif\t:     (202457201015)\n"
                + " Giantluigi Azka Zain\t:     (202457201023)\n"
                + "</pre>"
                + "<p></p>"
                + "</body>"
                + "</html>";
        labelAbout.setText(aboutText);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelAbout = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 248, 231));

        jPanel2.setBackground(new java.awt.Color(189, 195, 199));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ABOUT");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/images/icons8-about-43 (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(520, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(494, 494, 494))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        labelAbout.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelAbout.setForeground(new java.awt.Color(0, 0, 0));
        labelAbout.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(labelAbout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(labelAbout)
                .addGap(0, 555, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelAbout;
    // End of variables declaration//GEN-END:variables
}
