/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package latihanKu;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Insets;
import java.awt.print.PrinterException;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.sql.*;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class cetakStrukFrame extends javax.swing.JFrame {
    
    
    /**
     * Creates new form cetakStrukFrame
     */
    
    public cetakStrukFrame() {
        initComponents();
        print();
        setLocation(250, 100);
    }
        
    void print(){
        try {        
            String sql = "SELECT transaksi.NoFaktur, transaksi.ID_Customers, customers.nama, transaksi.TotalBeli, "
                    + "transaksi.tanggal FROM transaksi JOIN customers ON customers.ID_Customer = transaksi.ID_Customers ORDER BY transaksi.NoFaktur DESC LIMIT 1";
            Connection cnVar = koneksi.getKoneksi();
            Statement stVar = cnVar.createStatement();
            ResultSet rsVar = stVar.executeQuery(sql);
            
            String noFaktur = "";
            String idCustomer = "";
            String nama = "";
            int totalBeli = 0;
            String waktu = "";
            
            if (rsVar.next()) {
                noFaktur = rsVar.getString("NoFaktur");
                idCustomer = rsVar.getString("ID_Customers");
                nama = rsVar.getString("nama");
                totalBeli = rsVar.getInt("TotalBeli");
                waktu = rsVar.getString("tanggal");
            }
            
            DecimalFormatSymbols simbol = new DecimalFormatSymbols();
            simbol.setGroupingSeparator('.');
            simbol.setDecimalSeparator(',');
            DecimalFormat formatAngka = new DecimalFormat("#,###", simbol);

            
             String message = "==============================================\n\tWarung Kopi & PS Al-Wandee TENNAN\n\t       Jl. Mayjend D.I Panjaitan No. 90\n\t                 Kabupaten Nganjuk\n\t                      082331243098\n==============================================\n\t\t           tanggal  :  " + waktu + "\n\n"
                  + "No Faktur\t      :     " + noFaktur + "\n\n"
                  + "ID Customer\t      :     "  + idCustomer + "\n\n"
                  + "Nama Customer     :     " + nama + "\n\n"
                  + "Total Beli\t      :     Rp "  + formatAngka.format(totalBeli) + "\n\n"
                  + "==============================================\n\n"
                     + "\t     Terima kasih atas kunjungannya,\n"
                     + "\t           Silahkan datang kembali.\n\n\n\n\n"
                     + "\t\t\t                  Admin\n";
            
            rsVar.close();
            stVar.close();
            txtStruk.setText(message);
        
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Error : " + sQLException.getMessage());
        }
       txtStruk.setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtStruk = new javax.swing.JTextArea();
        buttonPrint = new javax.swing.JButton();
        buttonKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtStruk.setBackground(new java.awt.Color(255, 255, 255));
        txtStruk.setColumns(20);
        txtStruk.setForeground(new java.awt.Color(0, 0, 0));
        txtStruk.setLineWrap(true);
        txtStruk.setRows(5);
        txtStruk.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtStruk);

        buttonPrint.setBackground(new java.awt.Color(0, 123, 255));
        buttonPrint.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonPrint.setForeground(new java.awt.Color(255, 255, 255));
        buttonPrint.setText("PRINT");
        buttonPrint.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrintActionPerformed(evt);
            }
        });

        buttonKembali.setBackground(new java.awt.Color(211, 47, 47));
        buttonKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonKembali.setForeground(new java.awt.Color(255, 255, 255));
        buttonKembali.setText("KEMBALI");
        buttonKembali.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(buttonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonKembaliActionPerformed

    private void buttonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrintActionPerformed
        // TODO add your handling code here:
        try {
            txtStruk.print();
        } catch (PrinterException printerException) {
            Logger.getLogger(cetakStrukFrame.class.getName()).log(Level.SEVERE, null, printerException);
        }
    }//GEN-LAST:event_buttonPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cetakStrukFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKembali;
    private javax.swing.JButton buttonPrint;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea txtStruk;
    // End of variables declaration//GEN-END:variables
}
