/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package latihanKu;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class dashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form dashboardPanel
     */
    public dashboardPanel() {
        initComponents();
        jumlah();
        pengguna();
    }
    
    void jumlah(){
        try {
            
         Connection cnVar = koneksi.getKoneksi();
            
            Statement stVar = cnVar.createStatement();
            
            String SQLJumlahMakanan = "SELECT COUNT(id) AS jumlah FROM makanminum WHERE kategori = 'Makanan'";           
            ResultSet jmlMakanan = stVar.executeQuery(SQLJumlahMakanan);
            int jumlahMakanan = 0;
            if (jmlMakanan.next()) {
                jumlahMakanan = jmlMakanan.getInt("jumlah");
            }
          
            
            String SQLJumlahMinuman = "SELECT COUNT(id) AS jumlah FROM makanminum WHERE kategori = 'Minuman'";
            ResultSet jmlMinuman = stVar.executeQuery(SQLJumlahMinuman);
            int jumlahMinuman = 0;
            if (jmlMinuman.next()) {
                jumlahMinuman = jmlMinuman.getInt("jumlah");
            }
        
            
            String SQLJumlahPS = "SELECT COUNT(id) AS jumlahps FROM ps";
            ResultSet jmlPS = stVar.executeQuery(SQLJumlahPS);
            int jumlahPS = 0;
            if (jmlPS.next()) {
                jumlahPS = jmlPS.getInt("jumlahps");
            }
      
            labelMakanan.setText(String.valueOf(jumlahMakanan));
            labelMinuman.setText(String.valueOf(jumlahMinuman));
            labelPS.setText(String.valueOf(jumlahPS));           
            
        } catch (SQLException sQLException) {
             sQLException.printStackTrace();
             JOptionPane.showMessageDialog(null, sQLException.getMessage());
        }
        
    }
    
    void pengguna(){
        
        String sql = "SELECT nama FROM user";
        Connection cnVar = koneksi.getKoneksi();
        
        try {
            Statement stVar = cnVar.createStatement();
            ResultSet rsVar = stVar.executeQuery(sql);
            if (rsVar.next()) {
                String nama = rsVar.getString("nama");
                labelPengguna.setText(nama);
            }
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Error : " + sQLException.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        labelMakanan = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelPS = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        labelMinuman = new javax.swing.JLabel();
        labelPengguna = new javax.swing.JLabel();
        labelSelamatDatang = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 248, 231));

        jPanel2.setBackground(new java.awt.Color(255, 193, 7));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/images/icons8-take-away-food-64.png"))); // NOI18N
        jLabel3.setText("TOTAL MAKANAN");
        jLabel3.setIconTextGap(20);

        labelMakanan.setFont(new java.awt.Font("Segoe UI", 1, 56)); // NOI18N
        labelMakanan.setForeground(new java.awt.Color(255, 255, 255));
        labelMakanan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelMakanan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 35));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addContainerGap(73, Short.MAX_VALUE))
            .addComponent(labelMakanan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(labelMakanan, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(13, 71, 161));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/images/icons8-game-controller-64 (1).png"))); // NOI18N
        jLabel2.setText("TOTAL PLAY STATION");
        jLabel2.setIconTextGap(20);

        labelPS.setFont(new java.awt.Font("Segoe UI", 1, 56)); // NOI18N
        labelPS.setForeground(new java.awt.Color(255, 255, 255));
        labelPS.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPS.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 35));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(43, Short.MAX_VALUE))
            .addComponent(labelPS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(labelPS, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(109, 76, 65));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/images/icons8-coffee-cup-64.png"))); // NOI18N
        jLabel4.setText("TOTAL MINUMAN");
        jLabel4.setIconTextGap(20);

        labelMinuman.setFont(new java.awt.Font("Segoe UI", 1, 56)); // NOI18N
        labelMinuman.setForeground(new java.awt.Color(255, 255, 255));
        labelMinuman.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelMinuman.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 35));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addContainerGap(86, Short.MAX_VALUE))
            .addComponent(labelMinuman, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(labelMinuman, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
        );

        labelPengguna.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        labelPengguna.setForeground(new java.awt.Color(0, 0, 0));
        labelPengguna.setText("PENGGUNA");

        labelSelamatDatang.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        labelSelamatDatang.setForeground(new java.awt.Color(0, 0, 0));
        labelSelamatDatang.setText("SELAMAT DATANG,");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(labelSelamatDatang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelPengguna))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSelamatDatang)
                    .addComponent(labelPengguna))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(318, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel labelMakanan;
    private javax.swing.JLabel labelMinuman;
    private javax.swing.JLabel labelPS;
    private javax.swing.JLabel labelPengguna;
    private javax.swing.JLabel labelSelamatDatang;
    // End of variables declaration//GEN-END:variables
}
