/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package latihanKu;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class kelolaUserPanel extends javax.swing.JPanel {

    /**
     * Creates new form akunPanel
     */
    public kelolaUserPanel() {
        initComponents();
        reset();
        label();
    }
    
    void reset(){
        txtUsernameLama.setText(null);
        txtUsernameBaru.setText(null);
        txtPasswordBaru.setText(null);
        txtNamaPengguna.setText(null);
    }
    
    void label(){
        String noteLabel = "NB : Silahkan ganti Username lama anda dengan Username dan Password yang baru, jika ingin menggantinya. Dan mohon isi secara keseluruhan.";
        labelNB.setText(noteLabel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsernameBaru = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonSimpan = new javax.swing.JButton();
        txtUsernameLama = new javax.swing.JTextField();
        buttonBatal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNamaPengguna = new javax.swing.JTextField();
        labelNB = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxShowPassword = new javax.swing.JCheckBox();
        txtPasswordBaru = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(189, 195, 199));

        txtUsernameBaru.setBackground(new java.awt.Color(255, 255, 255));
        txtUsernameBaru.setForeground(new java.awt.Color(0, 0, 0));
        txtUsernameBaru.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("USERNAME LAMA");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("PASSWORD BARU");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("USERNAME BARU");

        buttonSimpan.setBackground(new java.awt.Color(40, 167, 69));
        buttonSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonSimpan.setForeground(new java.awt.Color(255, 255, 255));
        buttonSimpan.setText("SIMPAN");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        txtUsernameLama.setBackground(new java.awt.Color(255, 255, 255));
        txtUsernameLama.setForeground(new java.awt.Color(0, 0, 0));
        txtUsernameLama.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        buttonBatal.setBackground(new java.awt.Color(244, 67, 54));
        buttonBatal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonBatal.setForeground(new java.awt.Color(255, 255, 255));
        buttonBatal.setText("BATAL");
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("NAMA PENGGUNA");

        txtNamaPengguna.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaPengguna.setForeground(new java.awt.Color(0, 0, 0));
        txtNamaPengguna.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        labelNB.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelNB.setForeground(new java.awt.Color(0, 0, 0));
        labelNB.setText("jLabel5");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/images/WhatsApp Image 2025-05-17 at 14.08.31.jpg"))); // NOI18N

        cbxShowPassword.setForeground(new java.awt.Color(0, 0, 0));
        cbxShowPassword.setText("Show Password");
        cbxShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxShowPasswordActionPerformed(evt);
            }
        });

        txtPasswordBaru.setBackground(new java.awt.Color(255, 255, 255));
        txtPasswordBaru.setForeground(new java.awt.Color(0, 0, 0));
        txtPasswordBaru.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNB)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsernameLama, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtNamaPengguna, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtUsernameBaru, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(cbxShowPassword)
                            .addComponent(txtPasswordBaru))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 309, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(216, 216, 216))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtUsernameLama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtUsernameBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxShowPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPasswordBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtNamaPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45)
                .addComponent(labelNB)
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        String userLama = txtUsernameLama.getText();
        String userBaru = txtUsernameBaru.getText();
        String passBaru = txtPasswordBaru.getText();
        String pengguna = txtNamaPengguna.getText();
        
        if (txtUsernameLama.getText().isBlank() || txtUsernameBaru.getText().isBlank() || txtPasswordBaru.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Harap mengisi data keseluruhan", "Peringatan", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        try {
            String sql = "UPDATE user SET username = ?, password = md5(?), nama = ? WHERE username = ?";
            Connection cnVar = koneksi.getKoneksi();
            
            PreparedStatement psVar = cnVar.prepareStatement(sql);
            psVar.setString(1, userBaru);
            psVar.setString(2, passBaru);
            psVar.setString(3, pengguna);
            psVar.setString(4, userLama);
            
            int konfirmasi = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin merubah\nUsername dan Password?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            
            if (konfirmasi == JOptionPane.YES_OPTION) {
                int psVarUpdate = psVar.executeUpdate();
                
                if (psVarUpdate > 0) {                    
                    reset();
                        JOptionPane.showMessageDialog(null, "Username dan Password berhasil diubah");
                        this.getTopLevelAncestor().setVisible(false);
                        new loginFrame().setVisible(true);                    
                } else {
                    JOptionPane.showMessageDialog(null, "Username lama salah, Username dan Password gagal diubah");
                }
            }
            
            psVar.close();
            cnVar.close();
        } catch (SQLException sQLException) {
                JOptionPane.showMessageDialog(null, "Error : " + sQLException.getMessage());
        }
        reset();
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void cbxShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxShowPasswordActionPerformed
        // TODO add your handling code here:
        if (cbxShowPassword.isSelected()) {
            txtPasswordBaru.setEchoChar((char) 0);
        } else {
            txtPasswordBaru.setEchoChar(('*'));
        }
    }//GEN-LAST:event_cbxShowPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JCheckBox cbxShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelNB;
    private javax.swing.JTextField txtNamaPengguna;
    private javax.swing.JPasswordField txtPasswordBaru;
    private javax.swing.JTextField txtUsernameBaru;
    private javax.swing.JTextField txtUsernameLama;
    // End of variables declaration//GEN-END:variables
}
