/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package latihanKu;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ASUS
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form loginFrame
     */
    public mainFrame() {
        initComponents();
        mainControlPanel.removeAll();
        mainControlPanel.add(new dashboardPanel());
        mainControlPanel.revalidate();
        mainControlPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainFramePanel = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        buttonDashboard = new javax.swing.JButton();
        buttonPS = new javax.swing.JButton();
        buttonTransaksi = new javax.swing.JButton();
        buttonAbout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        makanminumanButtonPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        buttonAkun = new javax.swing.JButton();
        buttonLogout = new javax.swing.JButton();
        navbarPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelClose = new javax.swing.JLabel();
        mainControlPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainFramePanel.setBackground(new java.awt.Color(255, 255, 255));

        sidebarPanel.setBackground(new java.awt.Color(78, 52, 46));

        buttonDashboard.setBackground(new java.awt.Color(78, 52, 46));
        buttonDashboard.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        buttonDashboard.setForeground(new java.awt.Color(255, 255, 255));
        buttonDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/images/icons8-dashboard-24.png"))); // NOI18N
        buttonDashboard.setText("DASHBOARD");
        buttonDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonDashboard.setIconTextGap(10);
        buttonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDashboardActionPerformed(evt);
            }
        });

        buttonPS.setBackground(new java.awt.Color(78, 52, 46));
        buttonPS.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        buttonPS.setForeground(new java.awt.Color(255, 255, 255));
        buttonPS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/images/icons8-game-controller-24.png"))); // NOI18N
        buttonPS.setText("PLAY STATION");
        buttonPS.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonPS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonPS.setIconTextGap(10);
        buttonPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPSActionPerformed(evt);
            }
        });

        buttonTransaksi.setBackground(new java.awt.Color(78, 52, 46));
        buttonTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        buttonTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        buttonTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/images/icons8-transaction-24.png"))); // NOI18N
        buttonTransaksi.setText("TRANSAKSI");
        buttonTransaksi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonTransaksi.setIconTextGap(10);
        buttonTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTransaksiActionPerformed(evt);
            }
        });

        buttonAbout.setBackground(new java.awt.Color(78, 52, 46));
        buttonAbout.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        buttonAbout.setForeground(new java.awt.Color(255, 255, 255));
        buttonAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/images/icons8-about-24.png"))); // NOI18N
        buttonAbout.setText("ABOUT");
        buttonAbout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonAbout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonAbout.setIconTextGap(10);
        buttonAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAboutActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/images/icons8-shop-64.png"))); // NOI18N

        makanminumanButtonPanel.setBackground(new java.awt.Color(78, 52, 46));
        makanminumanButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                makanminumanButtonPanelMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MAKANAN &");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MINUMAN");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/images/icons8-take-away-food-24.png"))); // NOI18N

        javax.swing.GroupLayout makanminumanButtonPanelLayout = new javax.swing.GroupLayout(makanminumanButtonPanel);
        makanminumanButtonPanel.setLayout(makanminumanButtonPanelLayout);
        makanminumanButtonPanelLayout.setHorizontalGroup(
            makanminumanButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(makanminumanButtonPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(makanminumanButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        makanminumanButtonPanelLayout.setVerticalGroup(
            makanminumanButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(makanminumanButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(jLabel5)
                .addContainerGap())
            .addGroup(makanminumanButtonPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonAkun.setBackground(new java.awt.Color(78, 52, 46));
        buttonAkun.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        buttonAkun.setForeground(new java.awt.Color(255, 255, 255));
        buttonAkun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/images/icons8-person-24.png"))); // NOI18N
        buttonAkun.setText("KELOLA USER");
        buttonAkun.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonAkun.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonAkun.setIconTextGap(10);
        buttonAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAkunActionPerformed(evt);
            }
        });

        buttonLogout.setBackground(new java.awt.Color(78, 52, 46));
        buttonLogout.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        buttonLogout.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/images/icons8-logout-24.png"))); // NOI18N
        buttonLogout.setText("LOGOUT");
        buttonLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonLogout.setIconTextGap(10);
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonPS, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(buttonTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(buttonAbout, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(buttonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(makanminumanButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonAkun, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(buttonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(makanminumanButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonPS, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );

        navbarPanel.setBackground(new java.awt.Color(60, 47, 47));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/images/WhatsApp Image 2025-05-17 at 14.08.28.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AKAT - Aplikasi Kasir Al-Wandee TENNAN");

        labelClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/images/icons8-close-40.png"))); // NOI18N
        labelClose.setText("jLabel7");
        labelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout navbarPanelLayout = new javax.swing.GroupLayout(navbarPanel);
        navbarPanel.setLayout(navbarPanelLayout);
        navbarPanelLayout.setHorizontalGroup(
            navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 584, Short.MAX_VALUE)
                .addComponent(labelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        navbarPanelLayout.setVerticalGroup(
            navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbarPanelLayout.createSequentialGroup()
                        .addGroup(navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelClose)
                            .addComponent(jLabel3))
                        .addGap(17, 17, 17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainControlPanel.setBackground(new java.awt.Color(255, 248, 231));
        mainControlPanel.setLayout(new java.awt.CardLayout(1, 1));

        javax.swing.GroupLayout mainFramePanelLayout = new javax.swing.GroupLayout(mainFramePanel);
        mainFramePanel.setLayout(mainFramePanelLayout);
        mainFramePanelLayout.setHorizontalGroup(
            mainFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navbarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainFramePanelLayout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainFramePanelLayout.setVerticalGroup(
            mainFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainFramePanelLayout.createSequentialGroup()
                .addComponent(navbarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainFramePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFramePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFramePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        // TODO add your handling code here:
         int yesOrNo = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (yesOrNo == JOptionPane.YES_OPTION) {
          new loginFrame().setVisible(true);
        dispose();  
        }
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void buttonTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTransaksiActionPerformed
        // TODO add your handling code here:
        mainControlPanel.removeAll();
        mainControlPanel.add(new transaksiPanel());
        mainControlPanel.revalidate();
        mainControlPanel.repaint();
    }//GEN-LAST:event_buttonTransaksiActionPerformed

    private void makanminumanButtonPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makanminumanButtonPanelMouseClicked
        // TODO add your handling code here:
         mainControlPanel.removeAll();
        mainControlPanel.add(new makanminumPanel());
        mainControlPanel.revalidate();
        mainControlPanel.repaint();
    }//GEN-LAST:event_makanminumanButtonPanelMouseClicked

    private void labelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCloseMouseClicked
        // TODO add your handling code here:
        
        int yesOrNo = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (yesOrNo == JOptionPane.YES_OPTION) {
          new loginFrame().setVisible(true);
        dispose();  
        }
        
    }//GEN-LAST:event_labelCloseMouseClicked

    private void buttonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDashboardActionPerformed
        // TODO add your handling code here:
        mainControlPanel.removeAll();
        mainControlPanel.add(new dashboardPanel());
        mainControlPanel.revalidate();
        mainControlPanel.repaint();
    }//GEN-LAST:event_buttonDashboardActionPerformed

    private void buttonPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPSActionPerformed
        // TODO add your handling code here:
         mainControlPanel.removeAll();
        mainControlPanel.add(new psPanel());
        mainControlPanel.revalidate();
        mainControlPanel.repaint();
    }//GEN-LAST:event_buttonPSActionPerformed

    private void buttonAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAboutActionPerformed
        // TODO add your handling code here:
        mainControlPanel.removeAll();
        mainControlPanel.add(new aboutPanel());
        mainControlPanel.revalidate();
        mainControlPanel.repaint();
    }//GEN-LAST:event_buttonAboutActionPerformed

    private void buttonAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAkunActionPerformed
        // TODO add your handling code here:
        mainControlPanel.removeAll();
        mainControlPanel.add(new kelolaUserPanel());
        mainControlPanel.revalidate();
        mainControlPanel.repaint();
    }//GEN-LAST:event_buttonAkunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAbout;
    private javax.swing.JButton buttonAkun;
    private javax.swing.JButton buttonDashboard;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonPS;
    private javax.swing.JButton buttonTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelClose;
    private javax.swing.JPanel mainControlPanel;
    private javax.swing.JPanel mainFramePanel;
    private javax.swing.JPanel makanminumanButtonPanel;
    private javax.swing.JPanel navbarPanel;
    private javax.swing.JPanel sidebarPanel;
    // End of variables declaration//GEN-END:variables
}
