/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package latihanKu;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class psPanel extends javax.swing.JPanel {

    /**
     * Creates new form psPanel
     */
    public psPanel() {
        initComponents();
        reset();
        data_ps();
    }
    
    void reset(){
        txtIDPS.setText(null);
        txtIDPS.setEditable(true);
        txtNamaPS.setText(null);
        txtHarga.setText(null);
        cbKategori.setSelectedItem(null);
    }
    
    void data_ps(){
        
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("ID Produk");
        model.addColumn("Nama Produk");
        model.addColumn("Kategori Produk");
        model.addColumn("Harga Produk");
        
        String sql = "SELECT * FROM ps";
        try {
            
            Connection cnVar = koneksi.getKoneksi();
            Statement psVar = cnVar.createStatement();
            ResultSet rsVar = psVar.executeQuery(sql);
            
            while (rsVar.next()) {                
                String idProduk = rsVar.getString("id");
                String namaProduk = rsVar.getString("nama");
                String kategoriProduk = rsVar.getString("kategori");
                String hargaProduk = rsVar.getString("harga");
                
                Object[] data = {idProduk, namaProduk, kategoriProduk, hargaProduk};
                model.addRow(data);
            }
            
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Gagal mengambil data " + sQLException.getMessage());
        }
        tablePS.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePS = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtIDPS = new javax.swing.JTextField();
        txtNamaPS = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        cbKategori = new javax.swing.JComboBox<>();
        buttonSimpan = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonBatal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 248, 231));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("KATEGORI PLAY STATION");

        tablePS.setBackground(new java.awt.Color(255, 255, 255));
        tablePS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tablePS.setForeground(new java.awt.Color(0, 0, 0));
        tablePS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePS);

        jPanel2.setBackground(new java.awt.Color(189, 195, 199));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("DATA PLAY STATION");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/images/icons8-game-controller-43 (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(404, 404, 404))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)))
                .addGap(14, 14, 14))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("HARGA PLAY STATION");

        jPanel3.setBackground(new java.awt.Color(189, 195, 199));

        txtIDPS.setBackground(new java.awt.Color(255, 255, 255));
        txtIDPS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIDPS.setForeground(new java.awt.Color(0, 0, 0));

        txtNamaPS.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaPS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNamaPS.setForeground(new java.awt.Color(0, 0, 0));

        txtHarga.setBackground(new java.awt.Color(255, 255, 255));
        txtHarga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHarga.setForeground(new java.awt.Color(0, 0, 0));

        cbKategori.setBackground(new java.awt.Color(255, 255, 255));
        cbKategori.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbKategori.setForeground(new java.awt.Color(0, 0, 0));
        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Play Station 3", "Play Station 4" }));

        buttonSimpan.setBackground(new java.awt.Color(40, 167, 69));
        buttonSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonSimpan.setForeground(new java.awt.Color(255, 255, 255));
        buttonSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/images/icons8-save-16.png"))); // NOI18N
        buttonSimpan.setText("SIMPAN");
        buttonSimpan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        buttonSimpan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        buttonSimpan.setIconTextGap(20);
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonHapus.setBackground(new java.awt.Color(211, 47, 47));
        buttonHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonHapus.setForeground(new java.awt.Color(255, 255, 255));
        buttonHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/images/icons8-bin-16.png"))); // NOI18N
        buttonHapus.setText("HAPUS");
        buttonHapus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        buttonHapus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        buttonHapus.setIconTextGap(25);
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonEdit.setBackground(new java.awt.Color(255, 193, 7));
        buttonEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonEdit.setForeground(new java.awt.Color(255, 255, 255));
        buttonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/images/icons8-edit-16.png"))); // NOI18N
        buttonEdit.setText("EDIT");
        buttonEdit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        buttonEdit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        buttonEdit.setIconTextGap(40);
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonBatal.setBackground(new java.awt.Color(0, 123, 255));
        buttonBatal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonBatal.setForeground(new java.awt.Color(255, 255, 255));
        buttonBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/images/icons8-cross-16.png"))); // NOI18N
        buttonBatal.setText("BATAL");
        buttonBatal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        buttonBatal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        buttonBatal.setIconTextGap(25);
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHarga)
                    .addComponent(cbKategori, 0, 325, Short.MAX_VALUE)
                    .addComponent(txtNamaPS)
                    .addComponent(txtIDPS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBatal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtIDPS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtNamaPS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID PLAY STATION");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("NAMA PLAY STATION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        if (txtIDPS.getText().isBlank() || txtNamaPS.getText().isBlank() || cbKategori.getSelectedItem() == null || txtHarga.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Harap mengisi data secara keseluruhan", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String idProduk = txtIDPS.getText();
        String namaProduk = txtNamaPS.getText();
        String hargaProduk = txtHarga.getText();
        String kategori = cbKategori.getSelectedItem().toString();
        
        try {
            
            String sql = "INSERT INTO ps VALUES (?, ?, ?, ?)";
            Connection cnVar = koneksi.getKoneksi();
            PreparedStatement psVar = cnVar.prepareStatement(sql);
            
            psVar.setString(1, idProduk);
            psVar.setString(2, namaProduk);
            psVar.setString(3, kategori);
            psVar.setString(4, hargaProduk);
            psVar.execute();
            
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Error, Data gagal disimpan " + sQLException.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        reset();
        data_ps();
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        // TODO add your handling code here:
        if (txtIDPS.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Harap memilih data yang ingin diubah", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String idProduk = txtIDPS.getText();
        String namaProduk = txtNamaPS.getText();
        String hargaProduk = txtHarga.getText();
        String kategori = cbKategori.getSelectedItem().toString();
        
        try {
            
            String sql = "UPDATE ps SET nama = ?, kategori = ?, harga = ? WHERE id = ?";
            Connection cnVar = koneksi.getKoneksi();
            PreparedStatement psVar = cnVar.prepareStatement(sql);
            
            psVar.setString(1, namaProduk);
            psVar.setString(2, kategori);
            psVar.setString(3, hargaProduk);
            psVar.setString(4, idProduk);
            psVar.execute();
            
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Error, Data gagal diubah" + sQLException.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        reset();
        data_ps();
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
         if (txtIDPS.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Harap memilih data yang ingin dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int yesOrNo = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (yesOrNo == JOptionPane.YES_OPTION) {
            String idProduk = txtIDPS.getText();
        
        try {
            
            String sql = "DELETE FROM ps WHERE id = ?";
            Connection cnVar = koneksi.getKoneksi();
            PreparedStatement psVar = cnVar.prepareStatement(sql);
            
            psVar.setString(1, idProduk);
            psVar.execute();
            
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            
          } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Error, Data gagal dihapus" + sQLException.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
          }
      }
        
        reset();
        data_ps();
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void tablePSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePSMouseClicked
        // TODO add your handling code here:
            int barisDipilih = tablePS.rowAtPoint(evt.getPoint());
            
            String idPS = tablePS.getValueAt(barisDipilih, 0).toString();
            String namaPS = tablePS.getValueAt(barisDipilih, 1).toString();
            String kategori = tablePS.getValueAt(barisDipilih, 2).toString();
            String harga = tablePS.getValueAt(barisDipilih, 3).toString();
            
            txtIDPS.setText(idPS);
            txtIDPS.setEditable(false);
            txtNamaPS.setText(namaPS);
            cbKategori.setSelectedItem(kategori);
            txtHarga.setText(harga);
       
    }//GEN-LAST:event_tablePSMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePS;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIDPS;
    private javax.swing.JTextField txtNamaPS;
    // End of variables declaration//GEN-END:variables
}
